# Generated by Django 3.2.8 on 2021-10-22 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='discapacidad',
            fields=[
                ('id_disc', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_disca', models.CharField(max_length=30, verbose_name='tipo de discapacidad ')),
                ('desc_disca', models.CharField(max_length=30, verbose_name='Descripcioroln')),
            ],
            options={
                'verbose_name': 'discapacidad',
                'verbose_name_plural': 'discapacidads',
            },
        ),
        migrations.CreateModel(
            name='usu_inf_pers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuip', models.CharField(max_length=30, verbose_name='número único de identificación personal ')),
                ('tipo_nuip', models.IntegerField(choices=[(0, 'Cédula de Ciudadanía'), (1, 'Tarjeta de Identidad'), (2, 'Cédula de Extranjería'), (3, 'Pasaporte'), (4, 'Permiso de Residencia')], default=0)),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres ')),
                ('apelllidos', models.CharField(max_length=60, verbose_name='Apellidos ')),
                ('nal', models.CharField(max_length=30, verbose_name='Nacionalidad ')),
                ('fch_naci', models.DateField(verbose_name='fecha de nacimiento')),
                ('gene', models.IntegerField(choices=[(0, 'Neutro'), (1, 'Femenino'), (2, 'Masculino'), (3, 'Intergénero'), (4, 'Transgénero'), (5, 'Sisgénero'), (6, 'Otro')], default=0)),
                ('ocup', models.CharField(max_length=30, verbose_name='Ocupacion ')),
                ('dir', models.CharField(max_length=100, verbose_name='Direccion ')),
                ('discap', models.BooleanField(default=False, verbose_name='¿Es una persona en condición de discapacidad?')),
                ('url_imag', models.URLField(verbose_name='url de la imagen personal.')),
                ('zona_hor', models.CharField(max_length=100, verbose_name='Zona Horaria ')),
                ('id_usu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_discap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusu.discapacidad')),
            ],
            options={
                'verbose_name': 'usu_inf_pers',
                'verbose_name_plural': 'usu_inf_perss',
            },
        ),
    ]
