# Generated by Django 3.2.8 on 2022-02-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_regusu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usu_inf_pers',
            name='gene',
            field=models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], default=0, verbose_name='Género'),
        ),
    ]
