# Generated by Django 3.2.8 on 2022-03-22 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_regusu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_acad',
            name='fch_fin',
            field=models.DateField(verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='form_acad',
            name='fch_ini',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='form_acad',
            name='menc',
            field=models.CharField(max_length=20, verbose_name='Mención '),
        ),
        migrations.AlterField(
            model_name='form_acad',
            name='token',
            field=models.CharField(max_length=20, verbose_name='Token de validación '),
        ),
        migrations.AlterField(
            model_name='usu_inf_pers',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
