# Generated by Django 3.2.8 on 2021-11-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_regusu', '0002_app_reg_usu_curs_dict_empleos_form_acad_habilidades_red_soc_rl_usu_inf_apps_rol_rl_usu_inf_contac_cu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discapacidad',
            name='desc_disca',
            field=models.CharField(max_length=30, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='discapacidad',
            name='tipo_disca',
            field=models.CharField(max_length=30, verbose_name='Tipo de discapacidad '),
        ),
    ]
