# Generated by Django 3.2.8 on 2022-02-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_regusu', '0002_alter_usu_inf_pers_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usu_inf_pers',
            name='gene',
            field=models.CharField(choices=[(0, 'Neutro'), (1, 'Femenino'), (2, 'Masculino'), (3, 'Intergénero'), (4, 'Transgénero'), (5, 'Sisgénero'), (6, 'Otro')], default=0, max_length=30, verbose_name='Género'),
        ),
    ]
