# Generated by Django 3.2.8 on 2022-02-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_regusu', '0004_alter_usu_inf_pers_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usu_inf_pers',
            name='gene',
            field=models.CharField(choices=[('Neutro', 'Neutro'), ('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Intergénero', 'Intergénero'), ('Transgénero', 'Transgénero'), ('Sisgénero', 'Sisgénero'), ('Otro', 'Otro')], default=0, max_length=30, verbose_name='Género'),
        ),
    ]
