# Generated by Django 3.2.8 on 2022-02-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_regusu', '0005_alter_usu_inf_pers_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usu_inf_pers',
            name='tipo_nuip',
            field=models.CharField(choices=[('Cédula', 'Cédula'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Cédula de Extranjería', 'Cédula de Extranjería'), ('Pasaporte', 'Pasaporte'), ('Permiso de Residencia', 'Permiso de Residencia')], default=0, max_length=30),
        ),
    ]
