# Generated by Django 3.2.8 on 2022-02-17 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_regusu', '0006_alter_usu_inf_pers_tipo_nuip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usu_inf_pers',
            name='apelllidos',
        ),
        migrations.RemoveField(
            model_name='usu_inf_pers',
            name='nombres',
        ),
    ]
