# Generated by Django 3.2.8 on 2022-02-17 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_modadm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usu',
            old_name='email',
            new_name='emailo',
        ),
    ]
