# Generated by Django 3.2.8 on 2022-02-21 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_modadm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usu',
            name='id_rol_sis',
        ),
    ]
