# Generated by Django 3.2.8 on 2021-12-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_modadm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Is_Partner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phoneNumber',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
