# Generated by Django 3.2.8 on 2022-03-22 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_modadm', '0002_remove_usu_id_rol_sis'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='id_sis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_modadm.listado_aplicativo'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='desc',
            field=models.CharField(max_length=50, verbose_name='Descripcion del Módulo'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='instalado',
            field=models.BooleanField(default=False, verbose_name='¿El módulo se encuentra instalado?'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='url_doc',
            field=models.URLField(verbose_name='URL Documentación'),
        ),
    ]
