# Generated by Django 3.2.8 on 2022-03-24 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('App_modadm', '0002_auto_20220324_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
