# Generated by Django 3.2.8 on 2021-12-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_modadm', '0002_auto_20211210_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
