# Generated by Django 3.2.8 on 2021-12-03 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_modadm', '0002_auto_20211202_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='id_ext_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_modadm.ext_app'),
        ),
        migrations.AddField(
            model_name='rol',
            name='id_ext_mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_modadm.ext_mod'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id_sis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_modadm.listado_aplicativo'),
        ),
    ]
