# Generated by Django 3.2.8 on 2021-12-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_modadm', '0003_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
    ]
