# Generated by Django 3.2.8 on 2021-12-03 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_modadm', '0003_auto_20211202_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ext_mod',
            name='mod_prin_ext',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='id_ext_app',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='id_ext_mod',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='id_sis',
        ),
        migrations.DeleteModel(
            name='ext_app',
        ),
        migrations.DeleteModel(
            name='ext_mod',
        ),
        migrations.DeleteModel(
            name='listado_aplicativo',
        ),
    ]
