# Generated by Django 3.2 on 2021-04-23 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_regusugr', '0001_initial'),
        ('App_modpry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_regpryi', '0002_app_reg_pry_id_mod_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='criterios',
            fields=[
                ('id_criterios_pry', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_creterio', models.CharField(max_length=40, verbose_name='Nombre del criterio')),
                ('desc_criterio', models.CharField(max_length=40, verbose_name='Descripcion del criterio')),
                ('objetivo_lograr', models.CharField(max_length=40, verbose_name='Objetivo a lograr')),
                ('porcentage_calificacion', models.CharField(max_length=40, verbose_name='porcentaje de calificacion')),
            ],
            options={
                'verbose_name': 'criterios',
                'verbose_name_plural': 'criterioss',
            },
        ),
        migrations.CreateModel(
            name='evalucion_pry',
            fields=[
                ('id_evalucion', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipos_evalucion', models.CharField(max_length=40, verbose_name='descripcion del tipo de evalucion ')),
                ('fech_ini', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de fin')),
                ('id_grup_bd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusugr.usugr')),
            ],
            options={
                'verbose_name': 'evalucion_pry',
                'verbose_name_plural': 'evalucion_prys',
            },
        ),
        migrations.CreateModel(
            name='tipos_evalucion',
            fields=[
                ('id_ipos_evalucion', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_tipos_evalucion', models.CharField(max_length=40, verbose_name='Nombre del tipo de evalucion ')),
                ('desc_tipos_evalucion', models.CharField(max_length=40, verbose_name='descripcion del tipo de evalucion ')),
            ],
            options={
                'verbose_name': 'tipos_evalucion',
                'verbose_name_plural': 'tipos_evalucions',
            },
        ),
        migrations.CreateModel(
            name='rel_evalucion_pry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evalucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_evapry.evalucion_pry')),
                ('id_investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_tipos_evalucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_evapry.tipos_evalucion')),
            ],
            options={
                'verbose_name': 'rel_evalucion_pry',
                'verbose_name_plural': 'rel_evalucion_prys',
            },
        ),
        migrations.CreateModel(
            name='criterios_pry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_logrado', models.BooleanField(default=False, verbose_name='si logro el objetivo')),
                ('id_criterios_pry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_evapry.criterios')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regpryi.inf_pry')),
            ],
            options={
                'verbose_name': 'criterios_pry',
                'verbose_name_plural': 'criterios_prys',
            },
        ),
        migrations.CreateModel(
            name='app_ev_pry',
            fields=[
                ('id_app_ev_pry', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_app_ev_pry', models.CharField(max_length=40, verbose_name='nombre de la App Evaluación  ')),
                ('desc_app_ev_pry', models.CharField(max_length=40, verbose_name='descripcion de la App  ')),
                ('status_app_ev_pry', models.BooleanField(default=False, verbose_name='estatus de la App Evaluación de Proyectos ')),
                ('id_mod_pry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_modpry.mod_pry')),
            ],
            options={
                'verbose_name': 'app_ev_pry',
                'verbose_name_plural': 'app_ev_prys',
            },
        ),
    ]
