# Generated by Django 3.2 on 2022-05-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mod_pry',
            fields=[
                ('id_mod_pry', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_mod_pry', models.CharField(max_length=40, verbose_name='Nombre ')),
                ('desc_mod_pry', models.CharField(max_length=40, verbose_name='Decripcion ')),
                ('status_mod_pry', models.BooleanField(default=False, verbose_name='¿status de la aplicacion.?')),
            ],
            options={
                'verbose_name': 'mod_pry',
                'verbose_name_plural': 'mod_prys',
            },
        ),
        migrations.CreateModel(
            name='pry_base',
            fields=[
                ('id_pry', models.AutoField(primary_key=True, serialize=False)),
                ('cod_pry', models.CharField(max_length=50, verbose_name='Código proyecto:')),
                ('nombre_pry', models.CharField(max_length=255, verbose_name='Nombre del proyecto: ')),
                ('desc_pry', models.CharField(max_length=255, verbose_name='Descripción del proyecto: ')),
                ('tipo_pry', models.IntegerField(choices=[(0, 'Ensayo'), (1, 'Disertación'), (2, 'intervención artística o creativa'), (3, 'Tesis'), (4, 'Trabajo de grado'), (5, 'Artículo científico'), (6, 'Estudio clínico'), (7, 'Estado de arte'), (8, 'Prototipo'), (9, 'Patente'), (10, 'Propiedad industrial'), (11, 'Revisión crítica')], default=0)),
                ('prop_pry', models.CharField(max_length=255, verbose_name='Propietario del proyecto: ')),
                ('est_pry', models.IntegerField(choices=[(0, 'Borrador'), (1, 'Diseño'), (2, 'Gestión'), (3, 'Diseño y gestión'), (4, 'Aprobación'), (5, 'Ejecución'), (6, 'Ejecutado'), (7, 'Archivado')], default=0)),
            ],
            options={
                'verbose_name': 'pry_base',
                'verbose_name_plural': 'proyectos base',
            },
        ),
    ]
