# Generated by Django 3.2 on 2022-05-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_modpry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conv_pry',
            fields=[
                ('id_mod_pry', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_conv_pry', models.CharField(max_length=40, verbose_name='Nombre ')),
                ('desc_conv_pry', models.CharField(max_length=40, verbose_name='Decripcion ')),
                ('status_conv_pry', models.BooleanField(default=False, verbose_name='¿status de la aplicacion.?')),
            ],
            options={
                'verbose_name': 'conv_pry',
                'verbose_name_plural': 'conv_prys',
            },
        ),
        migrations.CreateModel(
            name='crono_pry',
            fields=[
                ('id_crono_pry', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_crono_pry', models.CharField(max_length=40, verbose_name='Nombre ')),
                ('desc_crono_pry', models.CharField(max_length=40, verbose_name='Decripcion ')),
                ('status_crono_pry', models.BooleanField(default=False, verbose_name='¿status de la aplicacion.?')),
            ],
            options={
                'verbose_name': 'crono_pry',
                'verbose_name_plural': 'crono_prys',
            },
        ),
        migrations.CreateModel(
            name='dis_inv_pry',
            fields=[
                ('id_disinv_pry', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_disinv_pry', models.CharField(max_length=40, verbose_name='Nombre ')),
                ('desc_disinv_pry', models.CharField(max_length=40, verbose_name='Decripcion ')),
                ('status_disinv_pry', models.BooleanField(default=False, verbose_name='¿status de la aplicacion.?')),
            ],
            options={
                'verbose_name': 'dis_inv_pry',
                'verbose_name_plural': 'dis_inv_prys',
            },
        ),
        migrations.CreateModel(
            name='eva_pry',
            fields=[
                ('id_eva_pry', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_eva_pry', models.CharField(max_length=40, verbose_name='Nombre ')),
                ('desc_eva_pry', models.CharField(max_length=40, verbose_name='Decripcion ')),
                ('status_eva_pry', models.BooleanField(default=False, verbose_name='¿status de la aplicacion.?')),
            ],
            options={
                'verbose_name': 'eva_pry',
                'verbose_name_plural': 'eva_prys',
            },
        ),
        migrations.CreateModel(
            name='ges_pry',
            fields=[
                ('id_ges_pry', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_ges_pry', models.CharField(max_length=40, verbose_name='Nombre ')),
                ('desc_ges_pry', models.CharField(max_length=40, verbose_name='Decripcion ')),
                ('status_ges_pry', models.BooleanField(default=False, verbose_name='¿status de la aplicacion.?')),
            ],
            options={
                'verbose_name': 'ges_pry',
                'verbose_name_plural': 'ges_prys',
            },
        ),
        migrations.CreateModel(
            name='mlog_pry',
            fields=[
                ('id_mlog_pry', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_mlog_pry', models.CharField(max_length=40, verbose_name='Nombre ')),
                ('desc_mlog_pry', models.CharField(max_length=40, verbose_name='Decripcion ')),
                ('status_mlog_pry', models.BooleanField(default=False, verbose_name='¿status de la aplicacion.?')),
            ],
            options={
                'verbose_name': 'mlog_pry',
                'verbose_name_plural': 'mlog_prys',
            },
        ),
        migrations.CreateModel(
            name='recur_pry',
            fields=[
                ('id_recur_pry', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_recur_pry', models.CharField(max_length=40, verbose_name='Nombre ')),
                ('desc_recur_pry', models.CharField(max_length=40, verbose_name='Decripcion ')),
                ('status_recur_pry', models.BooleanField(default=False, verbose_name='¿status de la aplicacion.?')),
            ],
            options={
                'verbose_name': 'recur_pry',
                'verbose_name_plural': 'recur_prys',
            },
        ),
        migrations.CreateModel(
            name='regprgi_pry',
            fields=[
                ('id_regprgi', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_regprgi', models.CharField(max_length=40, verbose_name='Nombre ')),
                ('desc_regprgi', models.CharField(max_length=40, verbose_name='Decripcion ')),
                ('status_regprgi', models.BooleanField(default=False, verbose_name='¿status de la aplicacion.?')),
            ],
            options={
                'verbose_name': 'regprgi_pry',
                'verbose_name_plural': 'regprgi_prys',
            },
        ),
        migrations.CreateModel(
            name='regpry_pry',
            fields=[
                ('id_regpry', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_regpry', models.CharField(max_length=40, verbose_name='Nombre ')),
                ('desc_regpry', models.CharField(max_length=40, verbose_name='Decripcion ')),
                ('status_regpry', models.BooleanField(default=False, verbose_name='¿status de la aplicacion.?')),
            ],
            options={
                'verbose_name': 'reg_pry',
                'verbose_name_plural': 'reg_prys',
            },
        ),
        migrations.DeleteModel(
            name='pry_base',
        ),
    ]
