# Generated by Django 3.2.8 on 2021-11-09 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_modadm', '0001_initial'),
        ('App_regusugr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usugr',
            name='id_rol_app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_modadm.rol'),
        ),
    ]
