"""
Django settings for sigepi project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from django.urls import reverse_lazy
import os.path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--6md_0ipddbli==3j8n4%0t-bgrhx^4fja=mo8k4kydx0f^_c&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ '*' ]


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'rest_framework',
    # 'corsheaders',
]

SIGEPI_APPS = [
    'modadm.App_modadm', #Aplicación principal del módulo
    'modadm.App_regusu', #Aplicación de registro de usuario
    'modadm.App_regusui', #Aplicación de registro de usuario grupo
    '#modadm.App_regusugr', #Aplicación de registro de usuario institucional
#    'modadm.App_regpat', #Aplicación de registro de Patrocinadores
#    'modadm.App_regben', #Aplicación de registro de Beneficiarios
    #'modpry.App_modpry', #Aplicación principal del módulo
    #'modpry.App_regpryi', #Apl
    #'modpry.App_regpryi', #Aplicación de registro de proyecto de investigación
    #'modpry.App_regprgi', #Aplicación de registro de programa de investigación
    #'modpry.App_regppi', #Aplicación de registro de productos y procesos de investigación
#    'modpry.App_mlog', #Aplicación de marco lógico
    #'modpry.App_gespry', #Aplicación de gestión de proyectos de investigación
    #'modpry.App_evapry', #Aplicación de evaluación de proyectos de investigación
#    'modpry.App_disinv' #Aplicación de d
    'modcons.App_cons' #Aplicación de consultas general sigepi
]

# Aplicaciones de terceros, exernas
EXT_APPS = [
]

INSTALLED_APPS = DJANGO_APPS + SIGEPI_APPS + EXT_APPS

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modadm.App_regusu',                        
    'modadm.App_regusugr',    
    'modadm.App_modadm',   
    'modadm.App_regusui',   
    'modcons.App_cons',   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sigepi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [BASE_DIR / 'plantillas','plantillas/registro', 'modadm/App_regusu/plantillas'],
        #Soluciona el problema de index_adm.html
        'DIRS': [BASE_DIR / 'plantillas', 
            BASE_DIR / 'plantillas/admSigepi',
            BASE_DIR / 'plantillas/admSigepi/articulos',
            BASE_DIR / 'plantillas/admSigepi/articulos/App_modAdm',
            BASE_DIR / 'plantillas/admSigepi/articulos/App_regusu',
            BASE_DIR / 'plantillas/admSigepi/articulos/App_regusugr',
            BASE_DIR / 'plantillas/admSigepi/articulos/App_regusui',
            BASE_DIR / 'plantillas/admSigepi/cabeceras',
            BASE_DIR / 'plantillas/admSigepi/cuerpos',
            BASE_DIR / 'plantillas/admSigepi/formularios',
            BASE_DIR / 'plantillas/admSigepi/herramientas',
            BASE_DIR / 'plantillas/admSigepi/lado',
            BASE_DIR / 'plantillas/admSigepi/pies',
            BASE_DIR / 'plantillas/admSigepi/widgets',
            BASE_DIR / 'plantillas/consultas',
            BASE_DIR / 'plantillas/front',
            BASE_DIR / 'plantillas/front/articulos',
            BASE_DIR / 'plantillas/front/cabeceras',
            BASE_DIR / 'plantillas/front/cuerpos',
            BASE_DIR / 'plantillas/front/formularios',
            BASE_DIR / 'plantillas/front/herramientas',
            BASE_DIR / 'plantillas/front/lado',
            BASE_DIR / 'plantillas/fron/pies',
            BASE_DIR / 'plantillas/fron/widgets',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sigepi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

# LOGIN_REDIRECT_URL=[]
#
# LOGOUT_REDIRECT_URL=[]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
