# Generated by Django 3.2 on 2022-06-09 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_regusugr', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pry_base',
            fields=[
                ('id_pry', models.AutoField(primary_key=True, serialize=False)),
                ('cod_pry', models.CharField(max_length=50, verbose_name='Código proyecto:')),
                ('nombre_pry', models.CharField(max_length=255, verbose_name='Nombre del proyecto: ')),
                ('desc_pry', models.CharField(max_length=255, verbose_name='Descripción del proyecto: ')),
                ('tipo_pry', models.IntegerField(choices=[(0, 'Ensayo'), (1, 'Disertación'), (2, 'intervención artística o creativa'), (3, 'Tesis'), (4, 'Trabajo de grado'), (5, 'Artículo científico'), (6, 'Estudio clínico'), (7, 'Estado de arte'), (8, 'Prototipo'), (9, 'Patente'), (10, 'Propiedad industrial'), (11, 'Revisión crítica')], default=0)),
                ('est_pry', models.IntegerField(choices=[(0, 'Borrador'), (1, 'Diseño'), (2, 'Gestión'), (3, 'Diseño y gestión'), (4, 'Aprobación'), (5, 'Ejecución'), (6, 'Ejecutado'), (7, 'Archivado')], default=0)),
                ('pry_archi', models.IntegerField(choices=[(0, 'Proyecto no archivado'), (1, 'Proyecto archivado')], default=0)),
                ('id_usu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pry_base',
                'verbose_name_plural': 'proyectos base',
            },
        ),
        migrations.CreateModel(
            name='inf_pry',
            fields=[
                ('id_inf_pry', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del archivo del proyecto: ')),
                ('url_archivo', models.URLField(verbose_name='url del archivo del proyecto')),
                ('url_ap', models.URLField(verbose_name='url de la imágen de árbol de problemas')),
                ('url_ao', models.URLField(verbose_name='url de la imágen de árbol de objetivos')),
                ('obj_gen', models.CharField(max_length=255, verbose_name='Objetivo general: ')),
                ('obj_esp', models.CharField(max_length=255, verbose_name='Objetivos especificos: ')),
                ('id_gr_inv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_regusugr.usugr')),
            ],
            options={
                'verbose_name': 'inf_pry',
                'verbose_name_plural': 'inf_prys',
            },
        ),
    ]
