# Generated by Django 3.2.8 on 2022-02-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_regusui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usui_inf_inst',
            name='tipo_inst',
            field=models.IntegerField(choices=[('Cédula', 'Cédula'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Cédula de Extranjería', 'Cédula de Extranjería'), ('Pasaporte', 'Pasaporte'), ('Permiso de Residencia', 'Permiso de Residencia')], default=0, verbose_name='Tipo de institución o entidad'),
        ),
    ]
